type Ingredient{
  name: String!
  id: String!
  group: String!
  energy: Float!
  carbohydrates: Float!
  fat: Float!
  protein: Float!
  microNutrients: [microNutrient]!
}

type microNutrient @embedded{
  name: String!
  amount: Float!
  unit: String!
}